### ISSUE TITLE
Gather and/or duplicate metrics container

### ISSUE THREAD

**Issue by marminthibaut** [Ingensi/dockerbeat#38]
We have to choose between:

* gather all statistics (cpu, blkio, container, etc.) into a unique and big event
* remove the container event, and duplicate container information to all other metrics

We should compare to topbeat and packetbeat to see their logics.

**Comment by erwanncloarec** [comment]
Well in both Topbeat & Packetbeat, the events are separated. In Topbeat, the events are even seperated per process! I don't see why we should not do the same thing. 
It is a benefit because it is clearer in ES when it is seperated, and more easy to query. 
We can also have a benefit if there is a metric that no longer exist, we can still have the others.

**Comment by marminthibaut** [comment]
I think we could adopt the second choice: remove the container event, and duplicate container information to all other metrics.

**Comment by marminthibaut** [comment]
Nothing to do:

we keep the five types:

* container
* memory
* cpu
* net
* blkio
