### ISSUE TITLE
Network type output.

### ISSUE THREAD

**Issue by TheStigger** [Ingensi/dockerbeat#97]
Can't find information about network type in a container (like `bridge` or `host`). Is there any support for this function?

**Comment by erwanncloarec** [comment]
Dockerbeat aims to pull containers metrics, not their metadata. The problem here is we would have to pull every metrics like volumes, links, and many things if we would implement that. Those metadata are 
not changing with time, so it wouldn't be effective to pull that every X seconds.

@marminthibaut  and I already talked about a new Beat that would pull all the changes of a Docker engine, like a run of a container. That Beat could pull all that metadata, because it would only happen once.

**Comment by marminthibaut** [comment]
:+1:  @erwanncloarec 

We should develop a new beat called `dockereventbeat` :)

**Comment by erwanncloarec** [comment]
More like eventdockerbeat because of trademark issues

Le mer. 30 mars 2016 12:07, Thibaut Marmin <notifications@github.com> a
écrit :
